import type { CategoryProfile, IssueType } from "@/lib/types";

export const ISSUE_TYPE_OPTIONS: Array<{ value: IssueType; label: string }> = [
  { value: "mechanical", label: "Broken or loose part" },
  { value: "power", label: "Won't power or charge" },
  { value: "sound", label: "Sound or audio issue" },
  { value: "fabric", label: "Wear, tear, seam or strap" },
  { value: "performance", label: "Buttons, keys or performance problem" },
  { value: "surface", label: "Surface wear, dirt or cosmetic issue" },
  { value: "safety", label: "Feels unsafe to keep using" },
  { value: "unknown", label: "Not sure yet" },
];

export const CATEGORY_PROFILES: CategoryProfile[] = [
  {
    id: "headphones",
    label: "Headphones",
    description: "Wired or wireless listening gear that often fails at joints, pads or connectors.",
    materialFocus: "plastic shells, small speakers, copper wiring and foam pads",
    defaultRecommendation: "repair",
    defaultDifficulty: "medium",
    recoverableMonths: [6, 18],
    ecoMessage: "Small electronics become waste fast when one cable or pad fails before the rest of the device does.",
    quickActions: [
      "Test with another cable, dongle or device first.",
      "Inspect the plug, ear cup hinge and exposed wire for stress points.",
      "Replace pads or cable before replacing the whole unit.",
    ],
    recyclingHint: "If repair fails, send them to e-waste collection so metals and plastics do not end up mixed with general trash.",
    reuseIdea: "Turn the working speaker side, cable or ear pads into spare parts for another pair.",
    commonFailures: [
      {
        label: "One side has no sound",
        keywords: ["one side", "left side", "right side", "single ear", "solo un lado", "solo un audifono"],
        diagnosis: "A stressed cable, loose jack or internal solder point is likely interrupting one channel.",
        recommendation: "repair",
        difficulty: "medium",
        actions: [
          "Try a gentle cable wiggle test near the plug and ear cup to locate the weak point.",
          "If the cable is detachable, swap it first before opening the headphones.",
          "If only the plug end is failing, a plug replacement or local electronics repair shop is usually enough.",
        ],
        recoveredMonths: [8, 18],
        avoidedImpact: "A single solder or cable fix can keep a mixed-material audio device in use instead of replacing it early.",
      },
      {
        label: "Ear pads or headband are worn out",
        keywords: ["pads", "almohadilla", "headband", "cushion", "foam", "desgastado"],
        diagnosis: "The sound hardware may still be usable even if comfort materials have worn down.",
        recommendation: "repair",
        difficulty: "easy",
        actions: [
          "Measure the pads and look for universal replacements first.",
          "Add a washable fabric cover or wrap the headband before comfort damage gets worse.",
          "Clean dust and skin oil buildup before installing new pads.",
        ],
        recoveredMonths: [6, 12],
        avoidedImpact: "Replacing the soft parts is often enough to delay a full electronics replacement cycle.",
      },
    ],
  },
  {
    id: "chargers",
    label: "Chargers",
    description: "Phone, laptop or accessory chargers with frequent cable fatigue and connector stress.",
    materialFocus: "copper conductors, insulation, molded plugs and small power components",
    defaultRecommendation: "repair",
    defaultDifficulty: "medium",
    recoverableMonths: [4, 12],
    ecoMessage: "Chargers are thrown away early even when the failure is isolated to the connector or outer sheath.",
    quickActions: [
      "Check another outlet and another device before blaming the charger.",
      "Inspect the cable ends for fraying, heat marks or bent pins.",
      "Replace detachable cables before replacing the power brick.",
    ],
    recyclingHint: "If it overheats, sparks or stops charging entirely after basic checks, route it to certified e-waste recycling.",
    reuseIdea: "Keep any healthy detachable cable or USB adapter as a labeled spare for low-power devices.",
    commonFailures: [
      {
        label: "Frayed or split cable",
        keywords: ["frayed", "split cable", "pelado", "raja", "deshilachado"],
        diagnosis: "Outer insulation damage usually starts at the high-flex point near the connector.",
        recommendation: "repair",
        difficulty: "easy",
        actions: [
          "Stop using it if bare wire is visible.",
          "If the cable detaches, replace only the cable.",
          "If it is fixed to the brick, compare the cost of a safe rewiring service versus recycling it.",
        ],
        recoveredMonths: [4, 8],
        avoidedImpact: "Saving the adapter body and only replacing the weak cable avoids discarding a still-useful charger assembly.",
      },
      {
        label: "Overheating or burning smell",
        keywords: ["burning", "hot", "overheat", "huele quemado", "se calienta"],
        diagnosis: "Internal power regulation may be failing, which raises a safety risk.",
        recommendation: "recycle",
        difficulty: "hard",
        actions: [
          "Stop using the charger immediately.",
          "Do not tape over the problem or keep testing it repeatedly.",
          "Take it to an e-waste drop-off point and replace it with the right rated charger.",
        ],
        recoveredMonths: [0, 0],
        avoidedImpact: "Recycling a failing charger safely prevents damaged electronics from entering mixed trash and reduces fire risk.",
      },
    ],
  },
  {
    id: "mouse",
    label: "Mouse",
    description: "Everyday computer mice that often fail at switches, wheels and battery contacts.",
    materialFocus: "plastic shell, tactile switches, small PCB and sensor components",
    defaultRecommendation: "repair",
    defaultDifficulty: "easy",
    recoverableMonths: [6, 14],
    ecoMessage: "A sticky switch or weak wheel is often a tiny component issue, not a reason to replace the whole mouse.",
    quickActions: [
      "Test on another surface or device first.",
      "Clean dust from the sensor and wheel channel.",
      "Check battery contacts before opening the shell.",
    ],
    recyclingHint: "If the board has liquid damage or the shell is cracked around the electronics, send it to e-waste recycling.",
    reuseIdea: "Reuse the shell screws, skates or USB receiver as spare parts for another compatible mouse.",
    commonFailures: [
      {
        label: "Click is failing or double clicking",
        keywords: ["click", "double click", "doesn't click", "no hace clic", "clic mal"],
        diagnosis: "The microswitch is probably worn or full of dust, which is common on heavily used mice.",
        recommendation: "repair",
        difficulty: "medium",
        actions: [
          "Clean around the click hinge before opening the mouse.",
          "If the switch is worn, replacing a low-cost microswitch can restore the mouse.",
          "If you do not solder, take it to a repair café or electronics technician.",
        ],
        recoveredMonths: [8, 16],
        avoidedImpact: "Replacing one tiny switch can prevent an entire input device from becoming premature e-waste.",
      },
      {
        label: "Scroll wheel is inconsistent",
        keywords: ["wheel", "scroll", "rueda", "desplaza mal"],
        diagnosis: "Dust or wear inside the scroll encoder is likely causing skipped movement.",
        recommendation: "repair",
        difficulty: "easy",
        actions: [
          "Blow out dust gently and test again.",
          "Open the shell only if the wheel remains erratic after cleaning.",
          "If the encoder is too worn, compare repair effort with e-waste recycling.",
        ],
        recoveredMonths: [6, 12],
        avoidedImpact: "A quick cleanup or encoder swap keeps a small electronic accessory useful for much longer.",
      },
    ],
  },
  {
    id: "keyboard",
    label: "Keyboard",
    description: "Laptop or desktop keyboards where keycaps, switches and spills create partial failures.",
    materialFocus: "plastic keycaps, membrane or switches, PCB and lightweight metal parts",
    defaultRecommendation: "repair",
    defaultDifficulty: "medium",
    recoverableMonths: [8, 20],
    ecoMessage: "Keyboards are often still structurally sound when only a few keys or stabilizers need attention.",
    quickActions: [
      "Test whether the same keys fail on another device or layout.",
      "Remove surface debris before assuming a full hardware failure.",
      "Check if the keycap, switch or cable is the real culprit.",
    ],
    recyclingHint: "If a major spill has corroded the board and multiple rows are dead, recycle it as electronics.",
    reuseIdea: "Keep usable keycaps, switches or cables as labeled donor parts.",
    commonFailures: [
      {
        label: "A few keys do not respond",
        keywords: ["keys", "stuck key", "doesn't type", "tecla", "no escribe"],
        diagnosis: "Localized debris or a worn switch is more likely than total keyboard failure.",
        recommendation: "repair",
        difficulty: "easy",
        actions: [
          "Clean around the affected key first.",
          "Swap the switch or keycap if your keyboard supports it.",
          "If it is a membrane keyboard with several dead keys, compare repair effort with recycling.",
        ],
        recoveredMonths: [8, 16],
        avoidedImpact: "Fixing isolated key failures keeps a large mixed-plastic accessory in circulation instead of replacing it wholesale.",
      },
      {
        label: "Spill damage",
        keywords: ["spill", "coffee", "water", "liquid", "derrame", "agua"],
        diagnosis: "Moisture may be bridging contacts or starting corrosion under the keys.",
        recommendation: "repair",
        difficulty: "hard",
        actions: [
          "Disconnect it immediately and let it dry fully before retesting.",
          "Open it only if you can clean residue safely without bending the membrane.",
          "If multiple rows stay dead after drying, recycle it responsibly.",
        ],
        recoveredMonths: [4, 10],
        avoidedImpact: "Fast cleanup can save the keyboard and avoid replacing a device that mostly failed from residue, not age.",
      },
    ],
  },
  {
    id: "backpack",
    label: "Backpack",
    description: "Bags with broken straps, seams and zippers that are often fixable with basic sewing or patching.",
    materialFocus: "woven fabric, foam, zippers, buckles and stitching",
    defaultRecommendation: "repair",
    defaultDifficulty: "easy",
    recoverableMonths: [12, 24],
    ecoMessage: "Soft goods often leave service because of one seam, buckle or zipper even though the body still has years left.",
    quickActions: [
      "Inspect whether the tear is at fabric, seam, buckle or zipper.",
      "Reinforce high-stress points before the damage spreads.",
      "Patch inside and outside if the fabric is thinning.",
    ],
    recyclingHint: "If the fabric is rotten or mold-damaged beyond safe cleaning, discard only after salvaging reusable buckles or straps.",
    reuseIdea: "Convert usable fabric panels into pouches, cable wraps or protective sleeves.",
    commonFailures: [
      {
        label: "Broken strap or torn seam",
        keywords: ["strap", "correa", "seam", "tear", "torn", "rota"],
        diagnosis: "The load-bearing stitch line has likely failed before the rest of the bag.",
        recommendation: "repair",
        difficulty: "easy",
        actions: [
          "Re-stitch the seam with heavy thread or take it to a local tailor or cobbler.",
          "Add reinforcement tape or a patch behind the weak point.",
          "Reduce load temporarily until the repair is secure.",
        ],
        recoveredMonths: [12, 24],
        avoidedImpact: "One reinforced seam can keep a durable bag in use for another school or work cycle instead of replacing it.",
      },
      {
        label: "Zipper failure",
        keywords: ["zipper", "cremallera", "zip", "atasca"],
        diagnosis: "The slider may be worn or the teeth may be misaligned while the bag body still works.",
        recommendation: "repair",
        difficulty: "medium",
        actions: [
          "Check whether the slider is loose before replacing the full zipper.",
          "Lubricate lightly and straighten misaligned teeth carefully.",
          "If the zipper tape is torn, replace the zipper instead of the whole backpack.",
        ],
        recoveredMonths: [8, 18],
        avoidedImpact: "Replacing one zipper preserves a large amount of still-usable fabric, foam and hardware.",
      },
    ],
  },
  {
    id: "chair",
    label: "Chair",
    description: "Home or office chairs with loose joints, worn covers or weak casters.",
    materialFocus: "metal tubing, wood, upholstery foam, fabric and fasteners",
    defaultRecommendation: "repair",
    defaultDifficulty: "medium",
    recoverableMonths: [12, 36],
    ecoMessage: "Furniture holds a lot of material value, so a small repair can prevent a bulky disposal event.",
    quickActions: [
      "Check whether the problem is structure, upholstery or moving parts.",
      "Tighten hardware before assuming the frame is failing.",
      "Replace small wear parts like feet or casters first.",
    ],
    recyclingHint: "If the frame is cracked beyond safe load-bearing use, separate recyclable metal parts before disposing of the rest.",
    reuseIdea: "Reuse the frame or seat board in a bench, plant stand or workshop stool project.",
    commonFailures: [
      {
        label: "Loose leg or wobble",
        keywords: ["wobble", "loose leg", "coja", "tambalea", "floja"],
        diagnosis: "Fasteners or joints may have loosened under repeated load rather than the frame being fully ruined.",
        recommendation: "repair",
        difficulty: "medium",
        actions: [
          "Tighten all visible fasteners and test on level ground.",
          "Add wood glue, brackets or fresh bolts if the joint keeps shifting.",
          "Stop using it until the wobble is safely resolved.",
        ],
        recoveredMonths: [12, 24],
        avoidedImpact: "Stabilizing one joint can save a bulky item from disposal and avoid replacing a high-material furniture piece.",
      },
      {
        label: "Worn seat or upholstery",
        keywords: ["seat", "upholstery", "fabric", "foam", "asiento"],
        diagnosis: "Comfort materials are worn, but the chair frame may still be structurally sound.",
        recommendation: "reuse",
        difficulty: "medium",
        actions: [
          "Re-cover the seat pad or add a removable washable cover.",
          "If comfort cannot be restored, repurpose it as a workshop or storage chair.",
          "Only discard if the frame and seat base are both unsafe.",
        ],
        recoveredMonths: [8, 18],
        avoidedImpact: "Repurposing a stable chair avoids sending a large composite object to disposal over mainly cosmetic wear.",
      },
    ],
  },
  {
    id: "blender",
    label: "Blender",
    description: "Kitchen blenders where jars, seals and couplers often fail before the motor does.",
    materialFocus: "motor housing, glass or plastic jar, blade assembly and seals",
    defaultRecommendation: "repair",
    defaultDifficulty: "medium",
    recoverableMonths: [6, 18],
    ecoMessage: "Appliances are often replaced when only a seal, coupler or jar has worn out.",
    quickActions: [
      "Check whether the issue is the jar, blade, seal or motor base.",
      "Unplug it before inspecting the coupler or blade assembly.",
      "Look for replacement jars and gaskets before replacing the appliance.",
    ],
    recyclingHint: "If the motor smells burnt or the electronics fail repeatedly, recycle it through appliance or e-waste channels.",
    reuseIdea: "Reuse the jar for dry storage only if it is intact and no longer safe for powered blending.",
    commonFailures: [
      {
        label: "Leaking jar or seal",
        keywords: ["leak", "leaking", "gasket", "seal", "pierde", "gotea"],
        diagnosis: "The gasket or jar connection is likely worn while the motor base remains fine.",
        recommendation: "repair",
        difficulty: "easy",
        actions: [
          "Replace the gasket first and inspect for hairline cracks in the jar base.",
          "Tighten the blade assembly only to the recommended fit.",
          "Test with water before blending food again.",
        ],
        recoveredMonths: [6, 14],
        avoidedImpact: "Replacing one seal or jar component can prevent an otherwise functional kitchen appliance from being discarded.",
      },
      {
        label: "Motor smells burnt",
        keywords: ["burnt", "smoke", "motor", "olor a quemado", "humo"],
        diagnosis: "The motor may be overheating internally, which is a reliability and safety risk.",
        recommendation: "recycle",
        difficulty: "hard",
        actions: [
          "Stop using it immediately and unplug it.",
          "Do not keep testing it under load.",
          "Recycle it through small appliance or e-waste collection rather than general trash.",
        ],
        recoveredMonths: [0, 0],
        avoidedImpact: "Safe appliance recycling helps recover metal and electronic parts instead of sending a failed motor to landfill.",
      },
    ],
  },
  {
    id: "shoes",
    label: "Shoes",
    description: "Daily footwear with sole wear, loose stitching or heel separation.",
    materialFocus: "rubber, foam, textile uppers, adhesives and stitching",
    defaultRecommendation: "repair",
    defaultDifficulty: "easy",
    recoverableMonths: [6, 18],
    ecoMessage: "Footwear often needs one outsole or seam intervention long before the upper is done.",
    quickActions: [
      "Check whether the issue is sole separation, upper tear or inside wear.",
      "Clean the repair area before applying glue or taking it to a cobbler.",
      "Patch early before the tear reaches load-bearing seams.",
    ],
    recyclingHint: "If both the sole and upper are structurally failing, look for textile or footwear recycling before discarding.",
    reuseIdea: "Retire worn pairs into gardening, painting or workshop shoes before their final end of life.",
    commonFailures: [
      {
        label: "Sole is separating",
        keywords: ["sole", "separating", "despegada", "pegamento", "suela"],
        diagnosis: "The bond between the upper and sole is likely failing before the rest of the shoe.",
        recommendation: "repair",
        difficulty: "easy",
        actions: [
          "Clean and dry the gap fully before using shoe adhesive.",
          "Clamp or tape the repair while the adhesive cures.",
          "If the gap is large, ask a cobbler to re-bond or stitch it.",
        ],
        recoveredMonths: [6, 12],
        avoidedImpact: "A sole repair can extend the use of footwear that still has a serviceable upper and lining.",
      },
      {
        label: "Upper is too worn for daily use",
        keywords: ["worn upper", "holes", "hole", "agujero", "gastado"],
        diagnosis: "The shoe may no longer be ideal for daily wear but could still serve in lower-demand tasks.",
        recommendation: "reuse",
        difficulty: "easy",
        actions: [
          "Patch the upper if the hole is localized.",
          "Downgrade the pair to yard work, painting or rainy-day use.",
          "Recycle the pair through a footwear take-back point once both comfort and safety are gone.",
        ],
        recoveredMonths: [3, 8],
        avoidedImpact: "Repurposing partially worn footwear delays disposal and extracts more value from the materials already made.",
      },
    ],
  },
  {
    id: "clothing",
    label: "Clothing",
    description: "Garments with tears, missing buttons, stains or worn fabric panels.",
    materialFocus: "cotton, polyester blends, elastic trims, thread and buttons",
    defaultRecommendation: "repair",
    defaultDifficulty: "easy",
    recoverableMonths: [6, 24],
    ecoMessage: "Textiles often become waste over minor damage that can be patched, re-hemmed or repurposed.",
    quickActions: [
      "Identify whether the issue is seam, stain, elastic or missing hardware.",
      "Mend small tears before washing widens them.",
      "If daily wear is over, think of a lower-demand second life.",
    ],
    recyclingHint: "Discard only after checking whether your area accepts worn textiles for recycling or fiber recovery.",
    reuseIdea: "Turn fabric panels into cleaning cloths, tote bag patches or protective wraps.",
    commonFailures: [
      {
        label: "Loose seam, button or hem",
        keywords: ["seam", "button", "hem", "costura", "boton", "dobladillo"],
        diagnosis: "The garment likely needs a quick mending job rather than replacement.",
        recommendation: "repair",
        difficulty: "easy",
        actions: [
          "Re-sew the seam or button before the stress area widens.",
          "Use matching thread or visible mending if you want the repair to stand out intentionally.",
          "Wash on a gentler cycle after repair if the fabric is thinning.",
        ],
        recoveredMonths: [8, 18],
        avoidedImpact: "A ten-minute mend can keep a garment in rotation for another season instead of replacing it immediately.",
      },
      {
        label: "Set-in stain or worn fabric",
        keywords: ["stain", "mancha", "faded", "thin fabric", "decolorado"],
        diagnosis: "The garment may still be useful even if it no longer fits its original role.",
        recommendation: "reuse",
        difficulty: "easy",
        actions: [
          "Dye or patch it if the fabric is still strong enough.",
          "Move it into sleepwear, workout wear or cleaning-cloth duty.",
          "Recycle textile fibers when the fabric finally loses strength.",
        ],
        recoveredMonths: [4, 10],
        avoidedImpact: "Repurposing worn textiles slows the churn of low-value clothing waste and gets more use from the fabric already produced.",
      },
    ],
  },
  {
    id: "lamp",
    label: "Lamp",
    description: "Desk or floor lamps where bulbs, switches and cords fail independently.",
    materialFocus: "metal frame, wiring, switch hardware, bulb socket and shade materials",
    defaultRecommendation: "repair",
    defaultDifficulty: "medium",
    recoverableMonths: [12, 24],
    ecoMessage: "Lighting fixtures are often still fine when the failure sits in the bulb, switch or cord.",
    quickActions: [
      "Test a known working bulb first.",
      "Inspect the switch, plug and strain relief for wear.",
      "Stop using it if the socket is cracked or sparking.",
    ],
    recyclingHint: "Recycle bulbs, metal parts and electronic components separately when possible instead of binning the whole lamp.",
    reuseIdea: "Reuse the shade or frame in a decorative or plant-support setup if the wiring is beyond repair.",
    commonFailures: [
      {
        label: "Bulb or switch issue",
        keywords: ["bulb", "switch", "flicker", "parpadea", "interruptor"],
        diagnosis: "The wiring path likely has a minor interruption at the bulb, socket or switch.",
        recommendation: "repair",
        difficulty: "easy",
        actions: [
          "Swap the bulb first.",
          "If flicker remains, inspect the switch and tighten the bulb socket only when unplugged.",
          "Replace the switch assembly before replacing the whole fixture.",
        ],
        recoveredMonths: [12, 24],
        avoidedImpact: "Restoring a lamp through a bulb or switch fix avoids discarding a durable fixture over a small electrical part.",
      },
      {
        label: "Cord damage or sparks",
        keywords: ["spark", "sparks", "cord", "cable", "chispa", "enchufe"],
        diagnosis: "The power cord or socket may be unsafe and needs immediate attention.",
        recommendation: "recycle",
        difficulty: "hard",
        actions: [
          "Unplug it and stop testing it.",
          "If the frame is worth saving, have the cord replaced by a qualified repair person.",
          "Otherwise separate recyclable parts and dispose of the rest responsibly.",
        ],
        recoveredMonths: [0, 0],
        avoidedImpact: "Handling an unsafe lamp through repair or proper recycling prevents avoidable electrical waste and safety risk.",
      },
    ],
  },
];

export const CATEGORY_LABELS = CATEGORY_PROFILES.map(({ id, label }) => ({
  value: id,
  label,
}));

export const DEMO_CASES = [
  {
    objectName: "Headphones only work on one side",
    categoryId: "headphones",
    issueType: "sound",
    details: "The right ear goes silent unless I bend the cable near the plug.",
  },
  {
    objectName: "My backpack strap snapped",
    categoryId: "backpack",
    issueType: "fabric",
    details: "One shoulder strap tore away from the seam but the bag body is still strong.",
  },
  {
    objectName: "This mouse barely clicks",
    categoryId: "mouse",
    issueType: "performance",
    details: "Left click feels mushy and sometimes double clicks on its own.",
  },
] as const;
